spring.application.name=BT7_LTWeb

# Cấu hình CSDL SQL Server (thay đổi tên DB, username, password tương ứng)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LTWeb_BT7;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cấu hình Swagger 3 (Mục 4)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html